spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:config-client}
      password: ${CONFIG_SERVER_PASSWORD:config-dev-secret}
