upstream config-server {
    server config-server-1:8888;
    server config-server-2:8888;
}

server {
    listen 8888;

    location / {
        proxy_pass http://config-server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
