server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: authentication-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9091/eureka}

springdoc:
  swagger-ui:
    enabled: false

management:
  tracing:
    enabled: true
    propagation:
      produce: b3
      consume: b3
    sampling:
      probability: 1.0
    export:
      zipkin:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
