server:
  port: ${SERVER_PORT:8090}
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI:http://localhost:8082}
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:user-db}
    redis:
      sentinel:
        master: ${REDIS_SENTINEL_MASTER:mymaster}
        nodes: ${REDIS_SENTINEL_NODES:redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379}

internal:
  api:
    token: ${INTERNAL_API_TOKEN}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9091/eureka}

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"

springdoc:
  swagger-ui:
    enabled: false

management:
  tracing:
    enabled: true
    propagation:
      produce: b3
      consume: b3
    sampling:
      probability: 1.0
    export:
      zipkin:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s
