server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI:http://localhost:8082}
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:user-db}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9091/eureka}

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"

springdoc:
  swagger-ui:
    enabled: false

management:
  tracing:
    enabled: true
    propagation:
      produce: b3
      consume: b3
    sampling:
      probability: 1.0
    export:
      zipkin:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s
